projectFinal-main/RMS/urls.py
from http.client import HTTPResponse
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from django.urls import path



from . import views

urlpatterns = [
    
               path('',views.home, name="home" ),
               
               path('login',views.userLogin, name="login" ),
               
               path('logout',views.userLogout, name="logout" ),

               path('register',views.register, name="register" ),

               path('userprofile',views.userprofile, name="userprofile" ),
               
               path('companyprofile',views.companyprofile, name="companyprofile" ),
               
               path('department',views.department, name="department" ),

             
               path('noti',views.noti, name="noti" ),

               
               path('usercv',views.usercv, name="usercv" ),

                 
              path('companies',views.companies, name="companies" ),

              path('Editprof',views.Editprof, name="Editprof" ),

              path('EditJobReq/<int:job_id>/', views.EditJobReq, name='edit_job_req'),

              
              path('Editsection/<int:sec_id>/', views.Editsection, name='Editsection'),

              path('deletejob/<int:job_id>/', views.deletejob, name='deletejob'),

              path('deleteskill/<int:skill_id>/', views.deleteskill, name='deleteskill'),


              
              path('EditSkill/<int:skil_id>/', views.EditSkill, name='EditSkill'),


             path('deleteeducation/<int:edu_id>/', views.deleteeducation, name='deleteeducation'),

             
             path('Editeducation/<int:edu_id>/', views.Editeducation, name='Editeducation'),

              path('deleteexpeience/<int:exp_id>/', views.deleteexpeience, name='deleteexpeience'),


              path('Editedexperience/<int:exp_id>/', views.Editedexperience, name='Editedexperience'),


              
              path('deletesection/<int:sec_id>/', views.deletesection, name='deletesection'),

              
              path('deleteproject/<int:Project_id>/', views.deleteproject, name='deleteproject'),


              path('Editproject/<int:project_id>/', views.Editproject, name='Editproject'),

              
              path('deletecertificate/<int:certificate_id>/', views.deletecertificate, name='deletecertificate'),


              path('Editcertificate/<int:cer_id>/', views.Editcertificate, name='Editcertificate'),
              
               path('changepassword',views.changepassword, name="changepassword" ),

               path('Editcvinfo',views.Editcvinfo, name="Editcvinfo" ),

               path('usereducation',views.usereducation, name="usereducation" ),

                path('addusereducation',views.addusereducation, name="addusereducation" ),

                path('userexperience',views.userexperience, name="userexperience" ),

                path('adduserexperience',views.adduserexperience, name="adduserexperience" ),

                path('usercertificates',views.usercertificates, name="usercertificates" ),

                path('addusercertificates',views.addusercertificates, name="addusercertificates" ),

                path('userprojects',views.userprojects, name="userprojects" ),

                path('addproject',views.addproject, name="addproject" ),

                path('edituserbio',views.edituserbio, name="edituserbio" ),

                path('uservolant',views.uservolant, name="uservolant" ),

                path('editusercontact',views.editusercontact, name="editusercontact" ),

                path('userskills',views.userskills, name="userskills" ),

               path('addskills',views.addskills, name="addskills" ),

               
               path('addsection',views.addsection, name="addsection" ),
                
               path('JobRequirements/',views.JobRequirements, name="JobRequirements" ),

               path('NewJob/',views.NewJob, name="NewJob" ),

               path('Status/<int:job_id>/', views.Status, name='Status'),

               path('jobsStatus/', views.jobsStatus, name='jobsStatus'),

               path('JobsHistory/',views.JobsHistory, name="JobsHistory" ),
               

               path('EditCompanyProf',views.EditCompanyProf, name="EditCompanyProf" ),

               
               path('profileinfo',views.profileinfo, name="profileinfo" ),


               path('userinfo',views.userinfo, name="userinfo" ),

                path('welcome',views.welcome, name="welcome" ),
                path('similarity_form',views.similarity_form, name="similarity_form" ),
                path('similarity_result',views.similarity_result, name="similarity_result" ),

                

                path('companydepartment/<int:department_id>/', views.companydepartment, name='companydepartment'),

                path('applicantsdepartment', views.applicantsdepartment, name='applicantsdepartment'),

                path('companyPro/<int:company_id>/',views.companyPro, name="companyPro" ),

                path('companyPro/<int:company_id>/<int:job_id>/', views.companyPro, name='companyPro'),

                path('applicantprof/<int:applicant_id>/',views.applicantprof, name='applicantprof' ),
                
                path('applicantprof/<int:applicant_id>/<int:educations_id>/',views.applicantprof, name='applicantprof' ),

                
                path('usersections', views.usersections, name='usersections'),


                

               path('dashboard',views.dashboard, name="dashboard" ),

                path('deleteapplicant/', views.deleteapplicant, name='deleteapplicant'),
                path('delete_company/', views.delete_company, name='delete_company'),
                 path('delete_department/',views.delete_department, name='delete_department'),
                 path('addApplicantForAdmin/', views.addApplicantForAdmin, name='addApplicantForAdmin'),
                 path('addDepartmentForAdmin/', views.addDepartmentForAdmin, name='addDepartmentForAdmin'),
                   path('add_department/', views.add_department, name='add_department'),
                   path('companiesForAdmin/',views.companiesForAdmin, name='companiesForAdmin'),
                   path('applicantsForAdmin/',views.applicantsForAdmin, name='applicantsForAdmin'),
                   path('departmentForAdmin/',views.departmentForAdmin, name='departmentForAdmin'),
                   path('jobForAdmin/',views.jobForAdmin, name='jobForAdmin'),
                    path('editjobreqdash/<int:job_id>/',views.editjobreqdash, name='editjobreqdash'),
                     path('deletejobdash/<int:job_id>/', views.deletejobdash, name='deletejobdash'),
                     path('JobRequirementsdash/',views.JobRequirementsdash, name="JobRequirementsdash"),
                     path('cv_evaluation/', views.cv_evaluation, name='cv_evaluation'),                 
                     path('test/',views.education_data, name="test"),
                      path('apply_job/<int:job_id>/', views.apply_job, name='apply_job'),

                     path('home/', views.home, name='home'),

         path('company/<int:company_id>/follow_unfollow/', views.follow_unfollow_company, name='follow_unfollow_company'),
           path('followers/', views.followers, name='followers'),

] 


#urlpatterns += static[settings.MEDIA_URL , document_root =settings.MEDIA_ROOT]

projectFinal-main/cv/urls.py
from http.client import HTTPResponse
from django.contrib import admin
from django.urls import path,include 
from django.http import HttpResponse
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RMS.urls'))
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projectFinal-main/RMS/models.py
from django.db import models
from django.contrib.auth.models import Group,User




 
class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name=models.CharField(max_length=30,null=True)
    
    def __str__(self):
        return self.name
    
    


class company(models.Model):
    id = models.AutoField(primary_key=True)
    name= models.CharField(max_length=100,null=True)
    email=models.CharField(max_length=100,null=True)
    location=models.CharField(max_length=1000,null=True)
    describtion=models.CharField(max_length=1000,null=True)
    companytype=models.CharField(max_length=100,null=True)
    about=models.CharField(max_length=1000,null=True)
    website=models.CharField(max_length=100,null=True)
    phone=models.CharField(max_length=20,null=True)
    companyphoto=models.ImageField(blank=True,null=True,default="company.png")
    user=models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE,null=True)
    followers = models.ManyToManyField(User, related_name='followed_companies', blank=True)


    def __str__(self):
       return str(self.name) if self.name else ''
    

    def get_number_of_companies():
        return company.objects.count()
   
  



class Applicant(models.Model):
    id = models.AutoField(primary_key=True)
    name= models.CharField(max_length=20,null=True)
    email=models.CharField(max_length=100,null=True)
    phone= models.CharField(max_length=20,null=True)
    jobname=models.CharField(max_length=100,null=True)
    userphoto=models.ImageField(blank=True,null=True,default="user.png")
    biography=models.CharField(max_length=1000,null=True)
    about=models.CharField(max_length=1000,null=True)
    location=models.CharField(max_length=40,null=True)
    birthdate=models.DateField(max_length=40,null=True)
    volanteering=models.CharField(max_length=1000,null=True)
    user=models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE,null=True)
    def __str__(self):
         return str(self.name) if self.name else ''
    
    def get_number_of_applicants():
        return Applicant.objects.count()

 


class skils(models.Model):
   
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=True)
    applicant = models.ManyToManyField(Applicant)
    def __str__(self):
        return self.name

 
class project(models.Model):
    id = models.AutoField(primary_key=True)
    title=models.CharField(max_length=100,null=True)
    role=models.CharField(max_length=1000,null=True)
    tools=models.CharField(max_length=1000,null=True)
    describtion=models.CharField(max_length=1000,null=True)
    applicant = models.ManyToManyField(Applicant)    
     
    def __str__(self):
        return self.title




 
class workexperience(models.Model):
    id = models.AutoField(primary_key=True)
    companyworked=models.CharField(max_length=100,null=True)
    jobworked=models.CharField(max_length=1000,null=True)
    describtion=models.CharField(max_length=1000,null=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE,null=True) 
    
    def __str__(self):
        return self.id




from django.db import models
from django.utils import timezone

class job(models.Model):
    id = models.AutoField(primary_key=True)
    salary = models.CharField(max_length=20, null=True)
    title = models.CharField(max_length=30, null=True)
    location = models.CharField(max_length=40, null=True)
    education = models.CharField(max_length=1000, null=True)
    workexperience = models.CharField(max_length=1000, null=True)
    technicalskills = models.CharField(max_length=1000, null=True)
    achievements = models.CharField(max_length=1000, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    deletion_time = models.TimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True) 
    companies = models.ManyToManyField('company')
    applicants = models.ManyToManyField('Applicant')
    number_of_positions = models.IntegerField(default=1)  # New field
    

    def __str__(self):
        return self.title

    class Meta:
        get_latest_by = 'created_at'

    @staticmethod
    def get_number_of_jobs():
        return job.objects.count()

    def is_active_job(self):
        today = timezone.now().date()
        return self.is_active and self.start_date <= today <= self.end_date




class OtherSection(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    describtion=models.CharField(max_length=1000,null=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name



class certificate(models.Model):
    id = models.AutoField(primary_key=True)
    place=models.CharField(max_length=1000,null=True)
    major=models.CharField(max_length=1000,null=True)
    about=models.CharField(max_length=1000,null=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE,null=True)
   
    def __str__(self):
        return self.major
          
          

class education(models.Model):
    
    id = models.AutoField(primary_key=True)
    title=models.CharField(max_length=1000,null=True)
    degree=models.CharField(max_length=1000,null=True)
    major=models.CharField(max_length=1000,null=True)
    fromto=models.CharField(max_length=1000,null=True)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE,null=True)
   
    def __str__(self):
        return self.title
          

class cv(models.Model):
   
    def __str__(self):
        return self
    

class Item(models.Model):
    def __str__(self):
        return self






class jobstatus(models.Model):
    company = models.ForeignKey(company, on_delete=models.CASCADE)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    job = models.ForeignKey(job, on_delete=models.CASCADE)
    percentage = models.FloatField(default=0)

    def __str__(self):
         return str(self.job) if self.job else ''

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message    

projectFinal-main/RMS/templates/RMS/Editedexperience.html
{% extends 'RMS/main.html' %}
{% load static %}
{% block content %}






<div class="container"  style="margin-left: 150px;margin-top:100px;margin-left: 220px;">
    <div class="card" style="width:50rem; margin-left: 150px;background-color: rgb(255,255,255,0.1);">
        <div class="card-body">
            <h1 style="color:white" >EDIT Experince</h1>
            <hr>
            <form method="POST" action="" enctype="multipart/form-data">
               
                <div class="form-group">
                 {% csrf_token %}
                     {% for field in form %}
                        <label class="form-label">{{ field.label_tag }}</label>
                        {{ field }}
                    {% endfor %}
                </div>
                     <br>    
           <div class="input-field"style="width:600px;">
                <input type="submit" class="submit" value="Update">
            </div>
            </form>
           
        </div>
    </div>
</div>

<style>
   
    .form-group label {
        font-size: 20px;
         color:white;
    }
  
  
      .form-group input,
    .form-group select,
    .form-group textarea {
        height: 45px;
    width: 700px;
    border: none;
    outline: none;
    border-radius: 30px;
    color: #fff;
    padding: 0 0 0 42px;
    background: rgba(255,255,255,0.1);
    }
.submit{
    border: none;
    border-radius: 30px;
    font-size: 15px;
    height: 45px;
    outline: none;
    width: 20%;
    background: rgba(255,255,255,0.7);
    cursor: pointer;
    transition: .3s;
}
.submit:hover{
    box-shadow: 1px 5px 7px 1px rgba(0, 0, 0, 0.2);
}
.input-field .input{
    height: 45px;
    width: 20%;
    border: none;
    outline: none;
    border-radius: 30px;
    color: #fff;
    padding: 0 0 0 42px;
    background: rgba(255,255,255,0.1);
}
</style>
{% endblock %}

projectFinal-main/RMS/templates/RMS/NewJob.html
{% extends 'RMS/main.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet", href="{%static 'css/style.css'%}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Post</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
      }
  
      .post-container {
        max-width: 600px;
        margin: 100px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }
  
      .post-form {
        display: flex;
        flex-direction: column;
      }
  
      .post-form textarea {
        resize: none;
        height: 100px;
        margin-bottom: 20px;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 4px;
        font-size: 14px;
      }

      .post-form input{
        resize: none;
        height: 10px;
        width: 100px;
        margin-bottom: 20px;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 4px;

      }
  
      .post-form button {
        background-color: #1877f2;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
      }
    </style>
    <link rel="stylesheet", href="{%static 'css/style.css'%}">
</head>
<body>
  
    <div class="post-container">
      <h2>Create a New Job</h2>
      <form class="post-form">
        <textarea id="postContent" placeholder="Job Announcement"></textarea>
        <button type="button" onclick="submitPost()">Post</button>
      </form>
    </div>

    <script>
      function submitPost() {
        // In a real-world scenario, you would use JavaScript to handle the form submission,
        // possibly using AJAX to send data to a server for processing.
        // Here, we'll just log the post content to the console for demonstration purposes.
  
        var postContent = document.getElementById('postContent').value;
        console.log('Posted: ', postContent);
  
        // You can add further logic to send the data to the server or perform other actions.
      }
    </script>
</body>
</html>

{% endblock %}

projectFinal-main/RMS/templates/RMS/applicantprof.html
{% extends 'RMS/main.html' %}
{% load static %}


{% block content %}
<div class="containeruser"style="margin-top:60px;margin-left:0px;" >
    <div class="row "  >
        <div class="col-xl-8" style="width: 100%;margin-left:140px; ">
            <div class="cardpro" style="margin-top: 50px; ">
                <div class="card-body pb-0 "  >
                    <div class="row align-items-center"  >
                        <div class="col-md-3" >
                            <div class="text-center border-end" style="margin-bottom: 35px;">
                                <img src="{{ applicant_instance.userphoto.url}}" class="img-fluid avatar-xxl rounded-image" alt="" style="height: 160px; width:155px">
                                <h4 class=" font-size-20 mt-3 mb-2" style="font-size: 20px; color: #171730;">{{ applicant_instance.name }}</h4>
                                <h5 class="text-muted font-size-13 mb-0" style="font-size: 15px; ">{{ applicant_instance.jobname }}</h5>
                            </div>
                        </div><!-- end col -->
                        <div class="col-md-9">
                            <div class="ms-3">
                                <div style="margin-top: 30px;">
                                    <h4 class="card-title mb-2">Biography</h4>
                                    <p class="mb-0 text-muted">{{ applicant_instance.biography }}</p>
                                </div>
                                <div class="row my-4">
                                    <div class="col-md-12">
                                        <div>
                                            <p class="text-muted mb-2 fw-medium"><i class="mdi mdi-email-outline me-2"></i>{{  applicant_instance.email }}
                                            </p>
                                            <p class="text-muted fw-medium mb-0"><i class="mdi mdi-phone-in-talk-outline me-2"></i>{{ applicant_instance.phone }}
                                            </p>
                                           
                                        </div>
                                    </div><!-- end col -->
                                </div><!-- end row -->

                            </div>
                        </div><!-- end col -->
                    </div><!-- end row -->
                </div><!-- end card body -->
            </div><!-- end card -->
    
            <div class="card" style="float: left; width:73%;">


  
<div class="carded education-card">
    <div class="card-bodyed">
        <h2 class="card-titleed" style="color:black; margin-left:290px;margin-top:-10px;">Education</h2>
       
        <div class="education-item">
          {% for education in   applicant_educations %}
          <li style="list-style: none; margin-bottom: 20px; padding: 15px; border: 2px solid #3498db; border-radius: 12px; background-color: #ecf0f1;">
            <h3 style="color: #3498db;">{{ education.title }}</h3>
            <p class="font-size-13 mb-2" style="color: rgb(80, 47, 47); font-size: 20px;"><span style="color: black; font-size: 18px;">Degree: </span>{{ education.degree }}</p>
            <p class="font-size-13 mb-2" style="color: rgb(80, 47, 47); font-size: 20px;"><span style="color: black; font-size: 18px;">Major: </span>{{ education.major }}</p>
            <p class="font-size-13 mb-2" style="color: rgb(80, 47, 47); font-size: 20px;"><span style="color: black; font-size: 18px;">From-To: </span>{{ education.fromto }}</p>
           
            {% endfor %}
            </li>
        </div>
    </div>
</div>


              <div class="card-body" >
<div  style="margin: 15px 20px 10px 20px;">
                      <h4 class="card-title mb-4">Work Experince</h4>
                       {% for workexperience in applicant_instance.workexperience_set.all %}
                      <ul class="list-unstyled  mb-0">
                           <li style="list-style: none; margin-bottom: 20px; padding: 15px; border: 2px solid #3498db; border-radius: 12px; background-color: #ecf0f1;">
                            
                                <div class="card-body">
                                    <h5 class="card-title text-center mb-0 comp"style="color: #3498db; font-size: 18px; margin:20px;">{{ workexperience.companyworked }}</h5>
                                    <p class="card-subtitle mb-2 text-muted text-center det" style="color: black; font-size: 18px; padding-top:20px;">{{ workexperience.jobworked }}</p>
                                    <div style="color: black; font-size: 18px;">Details:</div>
                                    <p class="card-text">
                                       {{ workexperience.describtion }}  
                                    </p>
                                   
                                </div>
                          
                      </ul><!-- end ul -->

                       {% endfor %}

                  </div>
              </div><!-- end card-body -->
            </div><!-- end card -->

            <div class="col-xl-4" style="width:25%; float: right;">
              <div class="card">
                  <div class="card-body">
                      <div class="pb-2" style="padding-top: 10px; padding-left:10px;">
                          <h4 class="card-title mb-3">About</h4>
                          <p> {{ request.user.applicant.about }}</p>
                          
                      </div>
                      
                  </div><!-- end cardbody -->
              </div><!-- end card -->
      
              <div class="card">
                <div class="card-body" >
                    <div>
                        <h4 class="card-title mb-4">Personal Details</h4>
                        <div class="table-responsive table-responsive-sm" >
                            <table class="table mb-0">
                                <tbody  style="width:90%;">
                                    <tr>
                                        <th scope="row">Name</th>
                                        <td>{{ request.user.applicant.name }}</td>
                                    </tr><!-- end tr -->
                                    <tr>
                                        <th scope="row">Location</th>
                                        <td>{{ request.user.applicant.location }}</td>
                                    </tr><!-- end tr -->
                                    <tr>
                                        <th scope="row">Date of Birth</th>
                                        <td>{{ request.user.applicant.birthdate }}</td>
                                    </tr><!-- end tr -->
                                    <tr>
                                        <th scope="row">E-mail</th>
                                        <td>{{ request.user.applicant.email }}</td>
                                    </tr><!-- end tr -->
                                </tbody><!-- end tbody -->
                            </table><!-- end table -->
                        </div>
                    </div>
                </div><!-- end card body -->
            </div><!-- end card -->
            
      
  
              <hr>

             
     <div class="pt-2">
    <h4 class="card-title mb-4" style="color: white">Technical Skill</h4>
     <div class="d-flex gap-2 flex-wrap">
          {% for skils in applicant_instance.skils_set.all %}
      
          <span class="badge badge-soft-secondary p-2" style="background-color: #0D6EFD; color:#ffffff">{{skils.name }}</span> 
           {% endfor %} 
     </div>
      </div>


  
  <div class="cardvolant">
    <div class="card-bodyvolant">
        <h2 class="card-titlevolant">Volunteering</h2>

        <div class="volant-item">
            
            <p class="descriptionvolant">{{ request.user.applicant.volanteering }}</p>
        </div>

        
    </div>


      
            <div class="card" style="float: left; width:73%;">

                
            </div><!-- end card -->


    </div>   


    
        </div><!-- end col -->

             


            <div class="card" style="float: left; width:73%;">
            <div class="card-body" >
                    <div  style="margin: 15px 20px 10px 20px;">
                     
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <h4 class="card-title mb-0 " style="margin-left:300px;vmargin-top:2px;">Certificates</h4></div>
                        {% for certificate in applicant_instance.certificate_set.all  %}
                        <ul class="list-unstyled mb-0">
                            <!-- Education Entry 1 -->
                            <li style="list-style: none; margin-bottom: 20px; padding: 15px; border: 2px solid #3498db; border-radius: 12px; background-color: #ecf0f1;">
                              <h5 class="lh-base mb-0" style="padding-bottom: 15px;color: #3498db;">{{certificate.place }}</h5>
                              <p class="font-size-13 mb-2" style="color: rgb(80, 47, 47); font-size: 20px;"><span style="color: black; font-size: 18px;">Major: </span>{{certificate.major }}</p>
                              <p class="font-size-13 mb-2" style="color: rgb(80, 47, 47); font-size: 20px;"><span style="color: black; font-size: 18px;">about: </span>{{certificate.about }}</p>
                             
                            </li>
                
                          </ul>
                          {% endfor %}
                    </div>
                </div><!-- end card-body -->

                <div>
                </div>   
   

                <br>
               
              <div class="card-body" style="margin: 15px 20px 10px 20px;">
                  <div>
                
                    <h4 class="card-title mb-4">Projects</h4>
                    <ul class="list-unstyled  mb-0">
                    {% for project in applicant_instance.project_set.all %}
                        <li style="list-style: none; margin-bottom: 20px; padding: 15px; border: 2px solid #3498db; border-radius: 12px; background-color: #ecf0f1;">
                            <h4 class="lh-base mb-2" style="color: #3498db;">{{ project.title }}</h4>
                            <p class="font-size-16 mb-2" style="color: #2c3e50;"><span style="color: #3498db;">Role: </span>{{ project.role }}</p>
                            <p class="font-size-16 mb-2" style="color: #2c3e50;"><span style="color: #3498db;">Tool: </span>{{ project.tools }}</p>
                            <div style="color: #3498db;">Description:</div>
                            <p style="color: #2c3e50; font-size: 16px; padding-left: 20px;">	
                                {{ project.describtion }}</p>
                            
                        </li>
                         {% endfor %}
                    </ul><!-- end ul -->
                </div>
                 
                 
                  
              <div class="card-body" style="margin: 15px 20px 10px 20px;">
                  <div>
                
                    <h4 class="card-title mb-4">Other Sections </h4>
                    <ul class="list-unstyled  mb-0">

                    {% for section in request.user.applicant.othersection_set.all %}
                        <li style="list-style: none; margin-bottom: 20px; padding: 15px; border: 2px solid #3498db; border-radius: 12px; background-color: #ecf0f1;">
                        <p class="font-size-16 mb-2" style="color: #2c3e50;"><span style="color: #3498db;"> </span>{{ section.name }}</p>
                        
                            <div style="color: #3498db;">Description:</div>
                            <p style="color: #2c3e50; font-size: 16px; padding-left: 20px;">	
                               {{ section.describtion }}
                            </p>
                            
                          </li>

                         
                                  
                        </li>
                     {% endfor %}
                    </ul><!-- end ul -->
                </div>
                
            </div><!-- end card-body -->
           
        </div><!-- end card -->
   
        

            
    
       
    </div>
    </div>


  </div>


{% endblock %}